version: '3'
services:
  mlflow:
    image: mlflow/mlflow:latest
    ports:
      - "5000:5000"
    volumes:
      - ./models:/app/models
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src

