version: "3.9"

services:
  data_service:
    build:
      context: ./src/data/build_data  # Path to the directory containing the Dockerfile
      dockerfile: Dockerfile
    container_name: data_service
    volumes:
      - ./logs:/app/logs  # Map logs directory
      - ./data:/app/data  # Map data directory
    environment:
      - DATA_PATH=${DATA_PATH}
      - IMPORT_DATA_LOGGER_PATH=${IMPORT_DATA_LOGGER_PATH}
    command: ["python3", "./src/data/build_data/import_raw_data.py"]

  training_service:
    build:
      context: ./src/models/train  # Path to the directory containing the Dockerfile
      dockerfile: Dockerfile
    container_name: training_service
    volumes:
      - ./logs:/app/logs  # Map logs directory
      - ./models:/app/models  # Map models directory
      - ./data:/app/data  # Map data directory
    environment:
      - TRAIN_MODEL_LOGGER_PATH=${TRAIN_MODEL_LOGGER_PATH}
      - TOKENIZER_CONFIG_PATH=${TOKENIZER_CONFIG_PATH}
      - LSTM_MODEL_PATH=${LSTM_MODEL_PATH}
      - VGG16_MODEL_PATH=${VGG16_MODEL_PATH}
      - BEST_WEIGHTS_PATH_PKL=${BEST_WEIGHTS_PATH_PKL}
      - DATA_PATH=${DATA_PATH}
      - IMAGES_PATH=${IMAGES_PATH}
      - CONCATENATED_MODEL_PATH=${CONCATENATED_MODEL_PATH}
    command: ["python3", "./src/models/train/train_model.py"]

  testing_service:
    build:
      context: ./src/models/predict  # Path to the directory containing the Dockerfile
      dockerfile: Dockerfile
    container_name: testing_service
    volumes:
      - ./logs:/app/logs  # Map logs directory
      - ./models:/app/models  # Map models directory
      - ./data:/app/data  # Map data directory
    environment:
      - TOKENIZER_CONFIG_PATH=${TOKENIZER_CONFIG_PATH}
      - LSTM_MODEL_PATH=${LSTM_MODEL_PATH}
      - VGG16_MODEL_PATH=${VGG16_MODEL_PATH}
      - BEST_WEIGHTS_PATH=${BEST_WEIGHTS_PATH}
      - MAPPER_PATH=${MAPPER_PATH}
      - DATASET_PATH=${DATASET_PATH}
      - IMAGES_PATH=${IMAGES_PATH}
      - PREDICTIONS_PATH=${PREDICTIONS_PATH}
      - TEST_MODEL_LOGGER_PATH=${TEST_MODEL_LOGGER_PATH}
    command: ["python3", "./src/models/train/train_model.py"]

  serving_service:
    build:
      context: ./src/models/serve  # Path to the directory containing the Dockerfile
      dockerfile: Dockerfile
    container_name: serving_service
    ports:
      - "8000:8000"  # Expose FastAPI service on port 8000
    volumes:
      - ./logs:/app/logs  # Map logs directory
      - ./models:/app/models  # Map models directory
    environment:
      - SERVING_LOGGER_PATH=${SERVING_LOGGER_PATH}
      - CONCATENATED_MODEL_PATH=${CONCATENATED_MODEL_PATH}
      - TOKENIZER_CONFIG_PATH=${TOKENIZER_CONFIG_PATH}
      - LSTM_MODEL_PATH=${LSTM_MODEL_PATH}
      - VGG16_MODEL_PATH=${VGG16_MODEL_PATH}
      - BEST_WEIGHTS_PATH=${BEST_WEIGHTS_PATH}
      - MAPPER_PATH=${MAPPER_PATH}
    command: ["uvicorn", "src.models.serve.serve_model_fastapi:app", "--host", "0.0.0.0", "--port", "8000"]