version: "3.9"
services:
  data_service:
    build:
      context: . # Path to the directory containing the Dockerfile
      dockerfile: ./src/data/build_data/Dockerfile
    container_name: data_service
    volumes:
      - ./logs:/app/logs # Map logs directory
      - ./data:/app/data # Map data directory
    environment:
      - DATA_PATH=${DATA_PATH}
      - IMPORT_DATA_LOGGER_PATH=${IMPORT_DATA_LOGGER_PATH}
      - PYTHONUNBUFFERED=1
  training_service:
    build:
      context: . # Path to the directory containing the Dockerfile
      dockerfile: ./src/models/train/Dockerfile
    container_name: training_service
    #depends_on:
    #  - data_service # Wait for data_service to start
    volumes:
      - ./logs:/app/logs  # Map logs directory
      - ./models:/app/models  # Map models directory
      - ./data:/app/data  # Map data directory
    environment:
      - TRAIN_MODEL_LOGGER_PATH=${TRAIN_MODEL_LOGGER_PATH}
      - TOKENIZER_CONFIG_PATH=${TOKENIZER_CONFIG_PATH}
      - LSTM_MODEL_PATH=${LSTM_MODEL_PATH}
      - VGG16_MODEL_PATH=${VGG16_MODEL_PATH}
      - BEST_WEIGHTS_PATH_PKL=${BEST_WEIGHTS_PATH_PKL}
      - DATA_PATH=${DATA_PATH}
      - IMAGES_PATH=${IMAGES_PATH}
      - CONCATENATED_MODEL_PATH=${CONCATENATED_MODEL_PATH}
      - MAPPER_PATH=${MAPPER_PATH}
      - BEST_WEIGHTS_PATH=${BEST_WEIGHTS_PATH}
      - MLFLOW_TRACKING_URI=${MLFLOW_TRACKING_URI}
      - MLFLOW_EXPERIMENT_NAME=${MLFLOW_EXPERIMENT_NAME}
      - DAGSHUB_USERNAME=${DAGSHUB_USERNAME}
      - DAGSHUB_TOKEN=${DAGSHUB_TOKEN}
      - PYTHONUNBUFFERED=1
  prediction_service:
    build:
      context: . # Path to the directory containing the Dockerfile
      dockerfile: ./src/models/predict/Dockerfile
    container_name: prediction_service
    #depends_on:
    #  - training_service # Wait for training to start
    volumes:
      - ./logs:/app/logs # Map logs directory
      - ./models:/app/models  # Map models directory
      - ./data:/app/data  # Map data directory
    environment:
      - TOKENIZER_CONFIG_PATH=${TOKENIZER_CONFIG_PATH}
      - LSTM_MODEL_PATH=${LSTM_MODEL_PATH}
      - VGG16_MODEL_PATH=${VGG16_MODEL_PATH}
      - BEST_WEIGHTS_PATH=${BEST_WEIGHTS_PATH}
      - MAPPER_PATH=${MAPPER_PATH}
      - DATASET_PATH=${DATASET_PATH}
      - IMAGES_PATH=${IMAGES_PATH}
      - PREDICTIONS_PATH=${PREDICTIONS_PATH}
      - TEST_MODEL_LOGGER_PATH=${TEST_MODEL_LOGGER_PATH}
      - PYTHONUNBUFFERED=1
  auth_service:
    build:
      context: .  # Path to the directory containing the Dockerfile for auth_service
      dockerfile: ./src/auth_service/Dockerfile
    container_name: auth_service
    ports:
      - "8011:8011"  # Expose port 8011 for the authentication service
    environment:
      - SECRET_KEY=${SECRET_KEY}  # Secret key for JWT
      - ALGORITHM=${ALGORITHM}    # Algorithm for JWT
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}  # Token expiration
      - AUTH_SERVICE_LOGGER_PATH=${AUTH_SERVICE_LOGGER_PATH}  # Logger path for auth_service
    volumes:
      - ./logs:/app/logs  # Map logs directory for auth_service
  serving_service:
    build:
      context: .  # Path to the directory containing the Dockerfile
      dockerfile: ./src/models/serve/Dockerfile
    container_name: serving_service
    #depends_on:
    #  - auth_service  # Wait for authentication to start
    ports:
      - "8000:8000"  # Expose FastAPI service on port 8000
    volumes:
      - ./logs:/app/logs  # Map logs directory
      - ./models:/app/models  # Map models directory
    environment:
      - SERVING_LOGGER_PATH=${SERVING_LOGGER_PATH}
      - CONCATENATED_MODEL_PATH=${CONCATENATED_MODEL_PATH}
      - TOKENIZER_CONFIG_PATH=${TOKENIZER_CONFIG_PATH}
      - LSTM_MODEL_PATH=${LSTM_MODEL_PATH}
      - VGG16_MODEL_PATH=${VGG16_MODEL_PATH}
      - BEST_WEIGHTS_PATH=${BEST_WEIGHTS_PATH}
      - MAPPER_PATH=${MAPPER_PATH}
      - PYTHONUNBUFFERED=1