stages:
  train:
    cmd: python src/models/train/train_model.py
    deps:
      - src/models/train/train_model.py
      - data/raw
    outs:
      # Retire les fichiers supprimés ou obsolètes ici
      # - models/best_weights.pkl
      # - models/best_weights.json
