{
 "title": "Product Classifier Monitoring",
 "description": "String monitoring of the API",
 "time": { "from": "2025-08-27T18:27:56.625Z", "to": "2025-08-27T19:27:56.625Z" },
 "panels": [
  {
   "title": "HTTP Requests Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (handler) (rate(http_request_duration_seconds_sum{ }[$__rate_interval]))",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Unauthorized requests on /predict",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{ handler=\"/predict\",status=\"4xx\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Successful requests on /predict",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{ handler=\"/predict\",status=\"2xx\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Unsuccessful requests on /predict",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{ handler=\"/predict\",status=\"5xx\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}